name: Bug report
description: Create a report to help us improve the project.
title: '[Bug]: '
labels: ['bug', 'needs triage']

body:
  - type: markdown
    attributes:
      value: |
        Follow the guidelines in this template to help us identify and fix the issue faster.
        - Write a clear and descriptive title for the issue.
        - Open one issue per bug. If you want to report multiple bugs, create separate issues for each.
        - Check the [open](https://github.com/knoodle-graph/knoodle-engine/issues) and [closed](https://github.com/knoodle-graph/knoodle-engine/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.
        - Verify if the bug is reproducible on the latest versions as it might have already been fixed.

  - type: input
    attributes:
      label: Affected version(s)
      description: Tested versions separated by commas
      placeholder: 1.3.0.dev [b290793], 1.3.1.stable
    validations:
      required: true

  - type: input
    attributes: 
      label: Platform(s) used
      description: Select the platform(s) where the bug occurs, separated by commas
      placeholder: Windows 10, Linux Ubuntu 20.04, macOS 10.15, Linux (arm64) Ubuntu 20.04
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue description
      description: |
        Describe the bug in detail.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Provide a detailed list of steps to reproduce the bug. 
        Include code snippets, screenshots, and any other relevant information.
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
          