name: Coverage

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: >-
        sudo apt update -y &&
        sudo apt install -y
        cmake
        g++
        build-essential
        ninja-build
        lcov

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      run: >-
        cmake
        -G Ninja
        -S "${{github.workspace}}"
        -B "${{github.workspace}}/build"
        -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
        -DCODE_COVERAGE:BOOL=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --build .

    - name: Test
      working-directory: "${{github.workspace}}/build"
      run: |
        ctest --no-tests=error

    - name: Create Coverage Reports
      run: |
        mkdir coverage
        lcov -c -d build/ -o coverage/lcov.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: coverage/lcov.info
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
