name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE.txt'
      - 'README.md'
      - 'third_party/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE.txt'
      - 'README.md'
      - 'third_party/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: >-
          sudo apt update -y &&
          sudo apt install -y
          cmake
          clang
          ninja-build
          doxygen

      - name: Configure CMake
        run: cmake -B build -S . -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DKNOODLE_BUILD_DOCS=ON -DBUILD_TESTING=OFF -DDOXYGEN_OUTPUT_DIRECTORY="${{ github.workspace }}/docs"

      - name: Build documentations
        run: cmake --build build --target docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/docs

