name: Deploy site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: >-
          sudo apt update -y &&
          sudo apt install -y
          cmake
          clang
          ninja-build
          doxygen
          graphviz

      - name: Configure CMake
        run: cmake -B build -S . -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DKNOODLE_BUILD_DOCS=ON -DBUILD_TESTING=OFF

      - name: Build documentations
        run: cmake --build build --target docs

      - name: Copy doxygen files
        run: |
          mkdir -p public
          cp -r build/docs/html/ ./public/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/html
