name: MacOS Build CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
        - 'doc/**'
        - 'misc/**'
        - 'LICENSE.txt'
        - 'README.md'
  push:
    branches: [main]
    paths-ignore:
      - 'doc/**'
      - 'misc/**'
      - 'LICENSE.txt'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: >-
        brew update &&
        brew install
        cmake
        gcc
        llvm

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      run: >-
        cmake
        -S "${{github.workspace}}"
        -B "${{github.workspace}}/build"
        -G "Xcode" -T "LLVM"
        -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --build . --config ${{matrix.configuration}}

    - name: Test
      working-directory: "${{github.workspace}}/build"
      run: |
        ctest -C ${{matrix.configuration}} --output-on-failure
