name: MacOS Build CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'doc/**'
      - 'misc/**'
      - '.issuetracker'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'knoodle-splash.svg'
      - 'LICENSE.txt'
      - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'doc/**'
      - 'misc/**'
      - '.issuetracker'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'knoodle-splash.svg'
      - 'LICENSE.txt'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: >-
        brew update &&
        brew install
        cmake
        gcc
        llvm

    - name: Setup Vulkan SDK
      run: |
        wget -o vulkan-sdk.zip https://sdk.lunarg.com/sdk/download/1.4.304.0/mac/vulkansdk-macos-1.4.304.0.zip
        unzip vulkan-sdk.zip
        rm vulkan-sdk.zip
        sudo ./InstallVulkan.app/Contents/MacOS/InstallVulkan --root "installation path" --accept-licenses --default-answer --confirm-command install
        vulkaninfo

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      run: >-
        cmake
        -S "${{github.workspace}}"
        -B "${{github.workspace}}/build"
        -G "Xcode" -T "LLVM"
        -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --build . --config ${{matrix.configuration}}

    - name: Test
      working-directory: "${{github.workspace}}/build"
      run: |
        ctest -C ${{matrix.configuration}} --output-on-failure
