name: Windows Build CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'doc/**'
      - 'misc/**'
      - '.issuetracker'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'knoodle-splash.svg'
      - 'LICENSE.txt'
      - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'doc/**'
      - 'misc/**'
      - '.issuetracker'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'knoodle-splash.svg'
      - 'LICENSE.txt'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      run: >-
        cmake
        -S "${{github.workspace}}"
        -B "${{github.workspace}}/build"
        -G "Visual Studio 17 2022" -A x64
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config ${{matrix.configuration}}

    - name: Test
      working-directory: "${{github.workspace}}/build"
      shell: bash
      run: |
        ctest -C ${{matrix.configuration}} --output-on-failure
